### ISSUE TITLE
severe color issue

### ISSUE THREAD

**Issue by rebootl** [rawstudio/rawstudio#7]
Hello
Really love the app to do the first image processing.
I'm using 2.0-14 on Arch Linux.
I'm no expert in raw processing but I do have a problem with white balance and I don't think it's normal.

Edit: Actually I'm not sure whether it's a white balance issue. So I changed the title/problem to color problem.

See the screenshot attached.
The small preview image looks fine, but the larger one is wrong. The leaves should be yellow. And despite trying really hard with different settings, I can't make them look right...
Also, after changing settings, the small preview and the big one, they never look the same.
This is so severe that it's currently unusable, unfortunately.

When using the ufraw gimp plugin it looks correct, right away (see below).
What could be the matter ?

Thanks a lot

![screen-rawstudio](https://cloud.githubusercontent.com/assets/3398507/10716329/9f2a71d2-7b35-11e5-86c0-fbbce41b074c.png)
![screen-ufraw](https://cloud.githubusercontent.com/assets/3398507/10716332/a8f67260-7b35-11e5-9aa3-86851bd9ee92.png)

I can't attach a sample raw here but could send you one. It's .ORF .

**Comment by abrander** [comment]
Thanks for reporting. Can you attach a sample raw image? (Or provide full make/model for your camera)

**Comment by rebootl** [comment]
raw image sample (12MB): http://cem.revamp-it.ch/files/PA250827.ORF
(I can't attach it here because of format and size)

Camera is Olympus PEN E-P1
Objective M.ZUIKO DIGITAL 14-42mm
The profile in rawstudio, I think autoselected (?), is OLYMPUS E-P1 Simple (dcp).
Maybe it's a problem with the camera db...

**Comment by rebootl** [comment]
Hello
I've just build the git version from so called Arch User Repository (AUR):
https://aur.archlinux.org/packages/rawstudio-git/

And it doesn't happen there. (However the UI has some issues then...)

So, I suspect it might have something to do with the official Arch Package:
https://projects.archlinux.org/svntogit/community.git/tree/trunk?h=packages/rawstudio
Two patches are applied there. I tried without the libpng15 patch, but building fails...

I think I'll report a bug to the Arch packager as well.
I'll try to build the regular (non-Arch) git version...

for reference
git-version from AUR, fixed colors but broken UI: thumbnails scrollbar, fonts, artifacts on larger preview after right-clicking (not visible here).
![screen-rawstudio2](https://cloud.githubusercontent.com/assets/3398507/10725956/1614af48-7bd0-11e5-8cd2-cec11ed86449.png)

**Comment by rebootl** [comment]
Reported to Arch bugtracker: https://bugs.archlinux.org/task/46875

**Comment by abrander** [comment]
Since this is already fixed in master, I'll close this issue. Thanks for reporting thou.

The UI problems are mostly due to GTK+ theming. You can switch Rawstudio to "System theme" in the preference dialog. That will fix most, if not all, issues.

**Comment by rebootl** [comment]
Hello. Yes, okay.
Using "System theme" fixes most of the issues. Thanks!
Exept the artifacts on the larger preview.
E.g. when I right click (context menu), or another window overlaps, it leaves artifacts...
See here:
![screen-rawstudio3](https://cloud.githubusercontent.com/assets/3398507/10768532/f7706e8e-7ce1-11e5-976c-5b9984bc9d9f.png)

**Comment by sergiomb2** [comment]
Also I have a better experience using "System theme" , IMHO and if it easy we should disable the other options until they got fixed .

**Comment by rebootl** [comment]
Just as an input / comment. You may want consider using git tags. Would be useful, since e.g. in this case Arch Linux is referring to a version 2, but I can't tell what git commit this is referring to.
Would be easily fixed by a tag.
Thanks

**Comment by toporoid** [comment]
Hello! The same problem with ALL raws from Canon 450d.
The problem dissolves after downgrade to exiv2-0.24-1 + rawstudio-2.0-12 from Arch Rollback Machine.

"System theme" doens't fix anything.

And interesting observation: I have 2 PCs, both are Arch with all updates. The problem exists on one and doesn't on another.
The PCs are very different, i7/radeon - this one is OK and core2duo/intel graphics on problematic. Packages and DE (Wmaker) are the same.

I can make further diagnostics.

**Comment by Makyui** [comment]
@abrander I'm having this exact same color issue with a Nikon D3100. Unfortunately, using the git version of RAWstudio (2.1-20160212-983bda1) doesn't fix the problem for me.

Sliding the hue slider around can get something close to the right colors, but there's still a whole lot of noise present. It's really ugly.
![2016-02-12-014857_1920x1200_scrot](https://cloud.githubusercontent.com/assets/1179830/13000783/ce76f404-d12c-11e5-944e-a01ed93a06aa.png)

On top of the color issue, the artifact/redraw issue mentioned by user rebootl above is there, too.
![2016-02-12-014948_1920x1200_scrot](https://cloud.githubusercontent.com/assets/1179830/13000788/dc9a2182-d12c-11e5-85f2-80dc436fb80d.png)

Sample RAW file: [https://drive.google.com/open?id=0B3Llry1Ed9yLNkRlZkZxTkRGc1U](url)

**Comment by sergiomb2** [comment]
Like I wrote in https://github.com/rawstudio/rawstudio/issues/8 , could you build and test https://github.com/sergiomb2/rawstudio Latest commit https://github.com/sergiomb2/rawstudio/commit/4209a92ac5ae236cc55b769b978c2630006bfd7e and report back please .

**Comment by Makyui** [comment]
Sorry for the long wait. After installing the latest commit, the result is the same.
![2016-02-12-222142_1920x1200_scrot](https://cloud.githubusercontent.com/assets/1179830/13025815/520c9a6e-d1df-11e5-81ae-0a95a1720b77.png)

**Comment by sergiomb2** [comment]
Hi , though was filter problems ...

**Comment by jerekupari** [comment]
I have similar looking colours with Nikon D90, and setting Hue at 60 degrees makes the image mostly normal colour. It's not a real workaround, but maybe it hints at what's wrong.

This is on Fedora 23, and with the rawstudio version that comes straight from the "app store".

**Comment by Makyui** [comment]
Yeah, I was hoping that it was a simple profile problem or something, but unfortunately I got the same thing when I ran some RAWs from my brother's Canon EOS. So it's probably not, unless they both happen to be borked.

Wish I had another linux box to test on, just to make sure it isn't something weird with my computer.

**Comment by sergiomb2** [comment]
Fedora 23 , have my commits (4209a92ac5ae236cc55b769b978c2630006bfd7e ) , I do the packaging.
These commits (from my repo) have rawspeed updated which could fix some filters for new cameras , but not problems of drag windows over the photos , this looks like more gtk refresh problems .

**Comment by jerekupari** [comment]
Narrowing it down: Also jpegs show in funny color, and raw from Canon 5Dm2. So this is not related to raw processing and camera profiles. Also it happens with all settings for the display color profile.

The preview strip thumbnail is in good color, and the preview is wrong. If I fix the preview with the +50–60 Hue, then the thumbnail goes wrong in the opposite direction. 
I think rebootl is describing something similar in the original report above.

I'm on Fedora 23 64 bit, Acer Aspire 1410. Only 2G memory, and intel graphics. I see Toporoid also had intel graphics on the problematic machine above:
https://github.com/rawstudio/rawstudio/issues/7#issuecomment-156799305
This machine had Ubuntu 14.04 before, there Rawstudio-daily from the rawstudio ppa worked fine.

I don't have the refresh problem, at least I can drag a Firefox window on top of the Rawstudio preview and nothing strange happens.

Should we reopen this, or move it to sergio's rawstudio, if the regression happened in there? What code does the broken Arch build use?

**Comment by jerekupari** [comment]
If I export the image the colors are wrong, just like the preview. But the thumbnail in queue looks right, just like the thumb in icon strip.

**Comment by sergiomb2** [comment]
Thanks for the detail report. Yes I think we should reopen it this issue.  
Looking at PPA for Rawstudio, 60 weeks ago starts fail to build and rawstudio code last update was from 2011-10-28. That is  why abrander  have to update rawstudio migrating to gtk3 etc  . I just did 2 or 3 little patches to fix segfault and also update rawspeed (to support more cameras), so IMHO the bug is in this project, no need to report on mine .

**Comment by Makyui** [comment]
Does that mean this could be a very old problem that somehow slipped through? I went through old commits trying to find where the problem started, and got as far back as mid 2011 before the packages wouldn't compile anymore, but the color problems were there the whole time. This struck me as pretty curious, since the Arch build that still worked was added to the official repository in 2014. But I don't know how to find what version it was built from, aside from "2.0" which is vague.

Exporting photos preserves the wrong colors, just like Jerekupari mentioned, and they [survive uploads to image sites](http://i.imgur.com/IPhEBxa.jpg). I use Nvidia graphics, if it helps, but since the color problems survive export it makes me think it's not just a graphics issue.

**Comment by sergiomb2** [comment]
Hello,
why do you thin is an old problem ? , I think is a new problem (on migration to gtk3) , after set my Nikon D3000 simple profile and enable lens, I don't see any problem , on deselect profile seems that I had a green filter .

if you want rawstudio-2.0.tar.gz  , you may unpack (with ark or file-roller or peazip) 
https://kojipkgs.fedoraproject.org//packages/rawstudio/2.0/18.fc22/src/rawstudio-2.0-18.fc22.src.rpm

**Comment by Makyui** [comment]
Mostly due to the comments about the old sources, and how old the release was that Arch's was built from (April 2011). You may be right, though.

Thanks for the source files.

**Comment by jerekupari** [comment]
Now I started my main desktop computer with Fedora 23 live usb drive. No funny colors there (with the version from the app store by sergio)!

Then I started this problematic small laptop with an Ubuntu 15.10 64 bit live usb. And compiled rawstudio's own git-master (983bda1). And there I got funny colors.

So it seems to be about the machine. Maybe I'll try a 32 bit distro next? Any suggestions?

The desktop is a i5-3570K/8G with integrated graphics.
The laptop is the aforementioned Acer Aspire 1410 with 2G of memory.

**Comment by jerekupari** [comment]
I created a few test images in Gimp, to see what it does to colors. It's quite fascinating! I saved them as png in Gimp and in Rawstudio, to eliminate lossy compression.
http://1drv.ms/1pcW4Nu
Maybe the last spectrum things are the most interesting.

(Download the stuff to see them uncompressed and see file names easily. rs-test4.png is the original from Gimp, the 'out' postfixes are from Rawstudio, and Rawstudio Hue-setting is added to the file name.)

Some observations:
1. It seems to be a predictable color change per pixel. (R1,G1,B1) always goes to (R2,G2,B2) regardless of color patch size, details etc. (Unless you use nonlocal tools like noise reduction or jpg compression.)
2. Neutral grays don't change much.
3. As you can see in the spectrum image, some color areas change smoothly, and some color areas change chaotically, creating a noise-like mess.
4. Exposure, Saturation, and Contrast still work as they should (except the chaotic areas sizzle in chaotic noise as you change them).
5. Hue, White balance and Color balance change where the chaotic color areas are. If you load my spectrum image in a healthy rawstudio and change Hue, the colors roll around. But in this sick rawstudio the healthy looking color areas stay in their place, but the noisy chaotic areas "walk around" the image.

**Comment by jerekupari** [comment]
I found another old laptop that runs rawstudio with the funny colors. Ubuntu 15.04 64-bit installed, and Fedora 23 32-bit live-usb. So again, it's about the machine, not distro or 32/64-bit.

The machine is a Fujitsu-Siemens Lifebook from 2007-2008, 3 GB memory, Nvidia graphics, proprietary drivers, I think.

**Comment by abrander** [comment]
On request from @jerekupari I'm reopening this for now.

**Comment by jerekupari** [comment]
Two more datapoints, I tried a HP Pavilion dv6000 from 2007 with amd cpu, and nvidia graphics, it's in funny color. And a new Thinkpad T560 (i5-6200/8G/intel hd520) is good color. So in my experience the bug happens in all hardware before circa 2010.

Also toporoid mentioned i7 ok / core2duo bad. And our Fujitsu-Siemens also has a core2duo T7500. 
I don't think @rebootl or @Makyui mentioned their machine ages or processor models.

Could it be related to avx vs sse issues? They seem to have some different code paths in Rawstudio. And the change to [avx](https://en.wikipedia.org/wiki/Advanced_Vector_Extensions) happened in 2011.

**Comment by jerekupari** [comment]
It's really difficult to follow what versions were tested, in the absence of proper version naming.

@rebootl was the working Arch build tested on the same machine that failed otherwise?

Or could it be that some different build settings might show or hide the problem?

I also have a vivid memory of using some reasonably new rawstudio on the Acer machine. I wrote Ubuntu 14.04 /rawstudio-daily above, not sure if that's correct, but probably is. Maybe I should try that again.

**Comment by rebootl** [comment]
> It's really difficult to follow what versions were tested, in the absence of proper version naming.
That's what I meant above... :)

> @rebootl was the working Arch build tested on the same machine that failed otherwise?
Yes, I think so.

> Or could it be that some different build settings might show or hide the problem?
Could be...
Maybe it could be driver or library related... idk.
Normally you would try to bisect such a bug using git. But somehow I wasn't able to reproduce it anymore at some point, it's long ago.

**Comment by jerekupari** [comment]
Thanks for the reply!

>  Maybe it could be driver or library related... idk.

Maybe, but I have used the exact same live usb stick on two different machines, the older one shows the issue, the newer one doesn't. And this happens at least on intel and nvidia GPUs.

So it seems that we need multiple things that together make this happen? In my experience the CPU needs to be pre-2011 (2007 amd, 2008 intel, 2010 intel bad, 2012 intel, 2016 intel good) and additionally maybe a distro from 2015-2016?

**Comment by abrander** [comment]
I'm pretty sure this issue is related to system ICC profiles.

The output from `$ colormgr get-devices` including the mentioned icc profile would be helpful in debugging this issue.

If we believe the issue is related to CPU features, one can start Rawstudio with `-d performance` to print a list of CPU features detected by Rawstudio.

**Comment by abrander** [comment]
Well. I'm closing this. If anyone has any more information, they are welcome to re-open.
